// Comprehensive mock data that matches the backend API structure
import { Hymn, Category, Author, SheetMusic } from "@/types";

export const mockCategories: Category[] = [
  { id: 1, name: "Worship", slug: "worship", description: "Hymns of worship and adoration" },
  { id: 2, name: "Praise", slug: "praise", description: "Hymns of praise and celebration" },
  { id: 3, name: "Thanksgiving", slug: "thanksgiving", description: "Hymns of gratitude and thanksgiving" },
  { id: 4, name: "Grace", slug: "grace", description: "Hymns about God's grace" },
  { id: 5, name: "Peace", slug: "peace", description: "Hymns of peace and comfort" },
  { id: 6, name: "Easter", slug: "easter", description: "Easter hymns" },
  { id: 7, name: "Christmas", slug: "christmas", description: "Christmas hymns" },
  { id: 8, name: "Lent", slug: "lent", description: "Lenten hymns" },
  { id: 9, name: "Advent", slug: "advent", description: "Advent hymns" },
];

export const mockAuthors: Author[] = [
  {
    id: 1,
    name: "John Newton",
    slug: "john-newton",
    biography: "English Anglican clergyman and hymn writer",
    birth_year: 1725,
    death_year: 1807,
  },
  {
    id: 2,
    name: "Carl Boberg",
    slug: "carl-boberg",
    biography: "Swedish pastor and hymn writer",
    birth_year: 1859,
    death_year: 1940,
  },
  {
    id: 3,
    name: "Fanny J. Crosby",
    slug: "fanny-j-crosby",
    biography: "American mission worker and hymn writer",
    birth_year: 1820,
    death_year: 1915,
  },
  {
    id: 4,
    name: "Thomas Chisholm",
    slug: "thomas-chisholm",
    biography: "American Methodist minister and hymn writer",
    birth_year: 1866,
    death_year: 1960,
  },
  {
    id: 5,
    name: "Horatio Spafford",
    slug: "horatio-spafford",
    biography: "American lawyer and hymn writer",
    birth_year: 1828,
    death_year: 1888,
  },
];

export const mockHymns: Hymn[] = [
  {
    id: 1,
    number: 101,
    title: "Amazing Grace",
    slug: "101-amazing-grace",
    author: 1,
    category: 4,
    language: "English",
    scripture_references: ["Ephesians 2:8-9", "2 Corinthians 12:9"],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    verses: [
      {
        verse_number: 1,
        is_chorus: false,
        text: "Amazing grace! How sweet the sound, that saved a wretch like me. I once was lost but now I'm found, was blind but now I see.",
        order: 1,
      },
      {
        verse_number: 2,
        is_chorus: false,
        text: "T'was grace that taught my heart to fear, and grace my fears relieved. How precious did that grace appear the hour I first believed.",
        order: 2,
      },
      {
        verse_number: 3,
        is_chorus: false,
        text: "Through many dangers, toils and snares, I have already come. 'Tis grace hath brought me safe thus far, and grace will lead me home.",
        order: 3,
      },
      {
        verse_number: 4,
        is_chorus: false,
        text: "When we've been there ten thousand years, bright shining as the sun. We've no less days to sing God's praise than when we've first begun.",
        order: 4,
      },
    ],
    history: "Written by John Newton in 1779. Newton was a former slave trader who experienced a spiritual conversion and became an abolitionist.",
    meter: "8.6.8.6",
    key_signature: "G Major",
    time_signature: "3/4",
    is_premium: false,
    is_featured: true,
    view_count: 0,
    sheetMusicUrl: "https://example.com/sheet-music/101.pdf",
    audioUrls: {
      piano: "https://archive.org/download/testmp3testfile/mpthreetest.mp3",
      soprano: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
      alto: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      tenor: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
      bass: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    },
  },
  {
    id: 2,
    number: 102,
    title: "How Great Thou Art",
    slug: "102-how-great-thou-art",
    author: 2,
    category: 2,
    language: "English",
    scripture_references: ["Psalm 145:3", "Romans 8:18"],
    created_at: "2024-01-02T00:00:00Z",
    updated_at: "2024-01-02T00:00:00Z",
    verses: [
      {
        verse_number: 1,
        is_chorus: false,
        text: "O Lord my God! When I in awesome wonder consider all the works Thy hands have made. I see the stars, I hear the rolling thunder, Thy power throughout the universe displayed.",
        order: 1,
      },
      {
        verse_number: 2,
        is_chorus: true,
        text: "Then sings my soul, my Savior God to Thee: How great Thou art! How great Thou art! Then sings my soul, my Savior God to Thee: How great Thou art! How great Thou art!",
        order: 2,
      },
      {
        verse_number: 3,
        is_chorus: false,
        text: "When through the woods and forest glades I wander and hear the birds sing sweetly in the trees. When I look down from lofty mountain grandeur and hear the brook and feel the gentle breeze.",
        order: 3,
      },
    ],
    history: "Originally a Swedish poem written by Carl Boberg in 1885. It was translated to English by Stuart Hine in 1949.",
    meter: "11.10.11.10",
    key_signature: "Bb Major",
    time_signature: "4/4",
    is_premium: false,
    is_featured: true,
    view_count: 0,
    sheetMusicUrl: "https://example.com/sheet-music/102.pdf",
    audioUrls: {
      piano: "https://archive.org/download/testmp3testfile/mpthreetest.mp3",
      soprano: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
      alto: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      tenor: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
      bass: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    },
  },
  {
    id: 3,
    number: 103,
    title: "Blessed Assurance",
    slug: "103-blessed-assurance",
    author: 3,
    category: 3,
    language: "English",
    scripture_references: ["Hebrews 10:22", "1 John 5:13"],
    created_at: "2024-01-03T00:00:00Z",
    updated_at: "2024-01-03T00:00:00Z",
    verses: [
      {
        verse_number: 1,
        is_chorus: false,
        text: "Blessed assurance, Jesus is mine! Oh, what a foretaste of glory divine! Heir of salvation, purchase of God, born of His Spirit, washed in His blood.",
        order: 1,
      },
      {
        verse_number: 2,
        is_chorus: true,
        text: "This is my story, this is my song, praising my Savior all the day long. This is my story, this is my song, praising my Savior all the day long.",
        order: 2,
      },
      {
        verse_number: 3,
        is_chorus: false,
        text: "Perfect submission, perfect delight, visions of rapture now burst on my sight. Angels descending bring from above echoes of mercy, whispers of love.",
        order: 3,
      },
    ],
    history: "Written by Fanny Crosby in 1873. Crosby wrote over 8,000 hymns despite being blind from infancy.",
    meter: "9.10.9.9",
    key_signature: "F Major",
    time_signature: "4/4",
    is_premium: false,
    is_featured: false,
    view_count: 0,
    sheetMusicUrl: "https://example.com/sheet-music/103.pdf",
    audioUrls: {
      piano: "https://archive.org/download/testmp3testfile/mpthreetest.mp3",
    },
  },
  {
    id: 4,
    number: 104,
    title: "Great Is Thy Faithfulness",
    slug: "104-great-is-thy-faithfulness",
    author: 4,
    category: 1,
    language: "English",
    scripture_references: ["Lamentations 3:22-23", "James 1:17"],
    created_at: "2024-01-04T00:00:00Z",
    updated_at: "2024-01-04T00:00:00Z",
    verses: [
      {
        verse_number: 1,
        is_chorus: false,
        text: "Great is Thy faithfulness, O God my Father. There is no shadow of turning with Thee. Thou changest not, Thy compassions they fail not. As Thou hast been, Thou forever wilt be.",
        order: 1,
      },
      {
        verse_number: 2,
        is_chorus: true,
        text: "Great is Thy faithfulness! Great is Thy faithfulness! Morning by morning new mercies I see. All I have needed Thy hand hath provided. Great is Thy faithfulness, Lord, unto me!",
        order: 2,
      },
      {
        verse_number: 3,
        is_chorus: false,
        text: "Summer and winter and springtime and harvest, sun, moon, and stars in their courses above join with all nature in manifold witness to Thy great faithfulness, mercy, and love.",
        order: 3,
      },
    ],
    history: "Written by Thomas Chisholm in 1923. The hymn is based on Lamentations 3:22-23 and emphasizes God's unchanging faithfulness.",
    meter: "11.10.11.10",
    key_signature: "Eb Major",
    time_signature: "3/4",
    is_premium: true,
    is_featured: true,
    view_count: 0,
    sheetMusicUrl: "https://example.com/sheet-music/104.pdf",
    audioUrls: {
      piano: "https://archive.org/download/testmp3testfile/mpthreetest.mp3",
      soprano: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
      alto: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      tenor: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
      bass: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    },
  },
  {
    id: 5,
    number: 105,
    title: "It Is Well With My Soul",
    slug: "105-it-is-well-with-my-soul",
    author: 5,
    category: 5,
    language: "English",
    scripture_references: ["2 Kings 4:26", "Philippians 4:7"],
    created_at: "2024-01-05T00:00:00Z",
    updated_at: "2024-01-05T00:00:00Z",
    verses: [
      {
        verse_number: 1,
        is_chorus: false,
        text: "When peace like a river, attendeth my way, when sorrows like sea billows roll. Whatever my lot, Thou hast taught me to say: It is well, it is well with my soul.",
        order: 1,
      },
      {
        verse_number: 2,
        is_chorus: true,
        text: "It is well with my soul, it is well, it is well with my soul.",
        order: 2,
      },
      {
        verse_number: 3,
        is_chorus: false,
        text: "Though Satan should buffet, though trials should come, let this blest assurance control: that Christ has regarded my helpless estate and hath shed His own blood for my soul.",
        order: 3,
      },
    ],
    history: "Written by Horatio Spafford in 1873 after he lost his four daughters in a shipwreck. Despite this tragedy, he wrote this hymn expressing his faith and trust in God.",
    meter: "11.8.11.9",
    key_signature: "Eb Major",
    time_signature: "4/4",
    is_premium: true,
    is_featured: false,
    view_count: 0,
    sheetMusicUrl: "https://example.com/sheet-music/105.pdf",
    audioUrls: {
      piano: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      soprano: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
      alto: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    },
  },
  // Add more mock hymns
  {
    id: 6,
    number: 106,
    title: "In Christ Alone",
    slug: "106-in-christ-alone",
    author: 1,
    category: 1,
    language: "English",
    scripture_references: ["1 Corinthians 3:11", "Colossians 2:9"],
    created_at: "2024-01-06T00:00:00Z",
    updated_at: "2024-01-06T00:00:00Z",
    verses: [
      {
        verse_number: 1,
        is_chorus: false,
        text: "In Christ alone my hope is found, He is my light, my strength, my song. This Cornerstone, this solid Ground, firm through the fiercest drought and storm.",
        order: 1,
      },
      {
        verse_number: 2,
        is_chorus: true,
        text: "In Christ alone, who took on flesh, fullness of God in helpless babe. This gift of love and righteousness, scorned by the ones He came to save.",
        order: 2,
      },
    ],
    history: "Modern hymn written in 2001 by Keith Getty and Stuart Townend.",
    meter: "8.8.8.8",
    key_signature: "D Major",
    time_signature: "4/4",
    is_premium: false,
    is_featured: false,
    view_count: 0,
  },
  {
    id: 7,
    number: 107,
    title: "Be Thou My Vision",
    slug: "107-be-thou-my-vision",
    author: 2,
    category: 1,
    language: "English",
    scripture_references: ["Psalm 16:8", "Proverbs 3:5-6"],
    created_at: "2024-01-07T00:00:00Z",
    updated_at: "2024-01-07T00:00:00Z",
    verses: [
      {
        verse_number: 1,
        is_chorus: false,
        text: "Be Thou my Vision, O Lord of my heart; Naught be all else to me, save that Thou art. Thou my best Thought, by day or by night, Waking or sleeping, Thy presence my light.",
        order: 1,
      },
    ],
    history: "Ancient Irish hymn translated by Mary Byrne in 1905.",
    meter: "10.10.10.10",
    key_signature: "Eb Major",
    time_signature: "3/4",
    is_premium: false,
    is_featured: false,
    view_count: 0,
  },
  {
    id: 8,
    number: 108,
    title: "Come Thou Fount",
    slug: "108-come-thou-fount",
    author: 1,
    category: 4,
    language: "English",
    scripture_references: ["1 Samuel 7:12", "Ephesians 2:8"],
    created_at: "2024-01-08T00:00:00Z",
    updated_at: "2024-01-08T00:00:00Z",
    verses: [
      {
        verse_number: 1,
        is_chorus: false,
        text: "Come, Thou Fount of every blessing, tune my heart to sing Thy grace; streams of mercy, never ceasing, call for songs of loudest praise.",
        order: 1,
      },
    ],
    history: "Written by Robert Robinson in 1758.",
    meter: "8.7.8.7",
    key_signature: "Eb Major",
    time_signature: "4/4",
    is_premium: false,
    is_featured: false,
    view_count: 0,
  },
];

export const mockSheetMusic: SheetMusic[] = [
  {
    id: 1,
    hymnId: 1,
    title: "Amazing Grace",
    composer: "John Newton",
    url: "https://example.com/sheet-music/101.pdf",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200&h=200&fit=crop",
  },
  {
    id: 2,
    hymnId: 2,
    title: "How Great Thou Art",
    composer: "Carl Boberg",
    url: "https://example.com/sheet-music/102.pdf",
    thumbnailUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=200&h=200&fit=crop",
  },
  {
    id: 3,
    hymnId: 4,
    title: "Great Is Thy Faithfulness",
    composer: "Thomas Chisholm",
    url: "https://example.com/sheet-music/104.pdf",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200&h=200&fit=crop",
  },
  {
    id: 4,
    title: "Prelude in C Major",
    composer: "Johann Sebastian Bach",
    url: "https://gmajormusictheory.org/Freebies/Intermediate/Bach/WTCPrel1.pdf",
    thumbnailUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=200&h=200&fit=crop",
  },
  {
    id: 5,
    title: "Moonlight Sonata",
    composer: "Ludwig van Beethoven",
    url: "https://example.com/sheet-music/moonlight-sonata.pdf",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200&h=200&fit=crop",
  },
  {
    id: 6,
    title: "Canon in D",
    composer: "Johann Pachelbel",
    url: "https://example.com/sheet-music/canon-d.pdf",
    thumbnailUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=200&h=200&fit=crop",
  },
];

// Helper function to simulate API delay
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

// Helper function to get hymn of the day (date-based)
export const getDailyHymn = (): Hymn => {
  const today = new Date().toDateString();
  let hash = 0;
  for (let i = 0; i < today.length; i++) {
    hash = today.charCodeAt(i) + ((hash << 5) - hash);
  }
  const index = Math.abs(hash) % mockHymns.length;
  return mockHymns[index];
};
